on:
  push:
    branches:
      - main

name: Create and Update Latest Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout TAStm32GUI code and merge into our python folder
        run: |
          git clone https://github.com/Zayitskin/TAStm32GUI/
          cp TAStm32GUI/hook.py /python/
          cp TAStm32GUI/main.py /python/
          cp TAStm32GUI/tasfile.py /python/
          cp TAStm32GUI/widgets.py /python/
      - name: Create Python Asset
        run: zip python.zip /python/*
      - name: Create Latest Release
        id: create_release
        uses: GongT/actions-recreate-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: latest
          release_name: Latest Compiled Firmware
          body: Auto build from ${{ github.sha }} (master)
          draft: false
          prerelease: false
      - name: Upload Python Release Asset
        id: upload-release-asset-python
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./python.zip
          asset_name: python.zip
          asset_content_type: application/zip
          
